version: '3.8'

services:
  javasql:
    image: mysql
    container_name: javasql
    ports:
      - "3300:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      # THIS IS IMPORTANT: Tells MySQL to create this database immediately
      # MYSQL_DATABASE: my_java_db 
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql

  java_app:
    build: . 
    image: hotel-management-java-app
    ports:
      - "8080:8080"
    environment:
      # Configuration for your Java app to connect to the DB
      DB_HOTELMANAGEMENT_URL: jdbc:mysql://javasql:3306/hotel_db?allowPublicKeyRetrieval=true&useSSL=false
      DB_USER: root
      DB_PASSWORD: 12345678
    # IMPORTANT: Wait for the database service (javasql) to be ready before starting the app
    depends_on:
      - javasql

volumes:
  # This declares the named volume 'mysql-data' so the javasql service can use it.
  mysql-data: